[package]
name = "timeops-jiff"
version = "0.1.0"
edition = "2021"

[dependencies]
jiff = { version = "0.1.13", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
